name: SFTP File Upload

on:
  push:
    branches:
      - main

jobs:
  sftp-upload:
    runs-on: ubuntu-latest

    services:
      sftp:
        image: atmoz/sftp
        env:
          SFTP_USERS: "testuser:password:1001"
        ports:
          - "2222:22"
        options:
          --name sftp-server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare file to upload
        run: echo "This is a test file" > testfile.txt

      - name: Test SFTP connection
        run: |
          sftp -P 2222 testuser@localhost << EOF
            pwd
            ls -la
            exit
          EOF

      - name: Transfer files via SFTP
        run: |
          sftp -P 2222 testuser@localhost << EOF
            cd /upload
            put -r ./files_to_upload/*
            bye
          EOF